# Generated by Django 6.0.5 on 2026-05-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_companysetupdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isMailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
